version: "3.7"
services:
  
  postgres:
    image: postgres:latest   
    container_name: postgres
    restart: always

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: rabbitmq
    restart: always
  
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver-local
    build:
      context: .
      dockerfile: src/AlbyOnContainers.IdentityServer/Dockerfile
    container_name: identityserver
    restart: unless-stopped
    
  hermes:
    image: ${DOCKER_REGISTRY-}hermes-local
    build:
      context: .
      dockerfile: src/AlbyOnContainers.Hermes/Dockerfile
    container_name: hermes
    restart: unless-stopped

  pollon:
    image: ${DOCKER_REGISTRY-}pollon-local
    build:
      context: .
      dockerfile: src/AlbyOnContainers.Pollon/Dockerfile
    container_name: pollon
    restart: unless-stopped
  
  sherlock:
    image: ${DOCKER_REGISTRY-}sherlock-local
    build:
      context: .
      dockerfile: src/AlbyOnContainers.Services.Catalog/Dockerfile
    container_name: sherlock
    restart: unless-stopped