version: "3.7"
services:
  
  postgres:
    image: postgres:latest   
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ${APPDATA}/ASP.NET/Sites/AlbyOnContainers/IdentityServer/postgres:/var/lib/postgresql

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    ports:
      - '8080:80'
      - '5341:5341'
    environment:
        ACCEPT_EULA: Y
    volumes:
      - ${APPDATA}/ASP.NET/Sites/AlbyOnContainers/IdentityServer/seq:/data

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - ${APPDATA}/ASP.NET/Sites/AlbyOnContainers/IdentityServer/rabbitmq/rabbitmq.conf:/etc/rabbitmq.conf:ro
      - ${APPDATA}/ASP.NET/Sites/AlbyOnContainers/IdentityServer/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
  
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver-local
    build:
      context: .
      dockerfile: src/AlbyOnContainers.IdentityServer/Dockerfile
    container_name: identityserver
    restart: unless-stopped
    depends_on:
      - "postgres"
    ports:
      - 5000:80
      - 5001:443
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "https://+:443;http://+:80"
      "ASPNETCORE_HTTPS_PORT": "443"
      "KESTREL__CERTIFICATES__DEFAULT__PATH": "/https/cert.pfx"
      "RABBITMQ__HOST": "rabbitmq"
      "EMAIL__NAME": "IdentityServer-Staging"
      "TOKENLIFETIME__MINUTES": "120"
      "TOKENLIFETIME__DAYS": "365"
      "HEALTHCHECKS__SELF__NAME": "self"
      "HEALTHCHECKS__SELF__TAGS__0": "identity"
      "HEALTHCHECKS__SELF__TAGS__1": "service"
      "HEALTHCHECKS__SELF__TAGS__2": "identityserver4"
      "HEALTHCHECKS__SELF__TAGS__3": "development"
      "HEALTHCHECKS__NPGSQL__NAME": "database"
      "HEALTHCHECKS__NPGSQL__TAGS__0": "identity"
      "HEALTHCHECKS__NPGSQL__TAGS__1": "db"
      "HEALTHCHECKS__NPGSQL__TAGS__2": "postgres"
      "HEALTHCHECKS__NPGSQL__TAGS__3": "development"
      "SERILOG__USING__0": "Serilog.Sinks.Console"
      "SERILOG__USING__1": "Serilog.Sinks.Seq"
      "SERILOG__MINIMUMLEVEL": "Information"
      "SERILOG__WRITETO__0__NAME": "Console"
      "SERILOG__WRITETO__1__NAME": "Seq"
      "SERILOG__WRITETO__1__ARGS__SERVERURL": "http://seq:5341"
      "SERILOG__ENRICH__0": "FromLogContext"
      "SERILOG__ENRICH__1": "WithMachineName"
      "SERILOG__ENRICH__2": "WithEnvironmentName"
      "SERILOG__ENRICH__3": "WithEnvironmentUserName"
      "SERILOG__ENRICH__4": "WithApplicationName"
      "SERILOG__PROPERTIES__APPLICATION": "AlbyOnContainers.IdentityServer.Development"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro
    
  hermes:
    image: ${DOCKER_REGISTRY-}hermes-local
    build:
      context: .
      dockerfile: src/AlbyOnContainers.Hermes/Dockerfile
    container_name: hermes
    restart: unless-stopped
    ports:
      - 5002:80
    depends_on:
      - "rabbitmq"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
      RABBITMQ__HOST: "rabbitmq"
      SERILOG__USING__0: "Serilog.Sinks.Console"
      SERILOG__USING__1: "Serilog.Sinks.Seq"
      SERILOG__MINIMUMLEVEL: "Information"
      SERILOG__WRITETO__0__NAME: "Console"
      SERILOG__WRITETO__1__NAME: "Seq"
      SERILOG__WRITETO__1__ARGS__SERVERURL: "http://seq:5341"
      SERILOG__ENRICH__0: "FromLogContext"
      SERILOG__ENRICH__1: "WithMachineName"
      SERILOG__ENRICH__2: "WithEnvironmentName"
      SERILOG__ENRICH__3: "WithEnvironmentUserName"
      SERILOG__ENRICH__4: "WithApplicationName"
      SERILOG__PROPERTIES__APPLICATION: "AlbyOnContainers.Hermes.Development"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

pollon:
  image: ${DOCKER_REGISTRY-}identityserver-local
    build:
      context: .
      dockerfile: src/AlbyOnContainers.Pollon/Dockerfile
  container_name: pollon
  restart: unless-stopped
  ports:
    - 5010:80
  environment:
    ASPNETCORE_ENVIRONMENT: "Development"
    ASPNETCORE_URLS: "http://+:5003"
    HEALTHCHECKS__SETEVALUTATIONTIMEINSECONS: "60"
    HEALTHCHECKS__SETMINIMUMSECONDSBETWEENFAILURENOTIFICATIONS: "240"
    HEALTHCHECKS__ENDPOINTS__0__NAME: "IdentityServer"
    HEALTHCHECKS__ENDPOINTS__0__URL: "https://localhost:5001/healthz"
    HEALTHCHECKS__ENDPOINTS__1__NAME: "Pollon"
    HEALTHCHECKS__ENDPOINTS__1__URL: "http://localhost:5002/healthz"
    HEALTHCHECKS__ENDPOINTS__2__NAME: "Hermes"
    HEALTHCHECKS__ENDPOINTS__2__URL: "http://localhost:5003/healthz"
    HEALTHCHECKS__ENDPOINTS__3__NAME: "CatalogAPI"
    HEALTHCHECKS__ENDPOINTS__3__URL: "http://localhost:5004/healthz"
    HEALTHCHECKS__CHECKS__SELF__NAME: "Self"
    HEALTHCHECKS__CHECKS__SELF__TAGS__0: "pollon"
    HEALTHCHECKS__CHECKS__SELF__TAGS__1: "health"
    HEALTHCHECKS__CHECKS__SELF__TAGS__2: "service"
    HEALTHCHECKS__CHECKS__SELF__TAGS__3: "ui"
    HEALTHCHECKS__CHECKS__NPGSQL__NAME: "Postgres"
    HEALTHCHECKS__CHECKS__NPGSQL__TAGS__0: "pollon"
    HEALTHCHECKS__CHECKS__NPGSQL__TAGS__1: "health"
    HEALTHCHECKS__CHECKS__NPGSQL__TAGS__2: "db"
    HEALTHCHECKS__CHECKS__NPGSQL__TAGS__3: "postgres"
    SERILOG__USING__0: "Serilog.Sinks.Console"
    SERILOG__USING__1: "Serilog.Sinks.Seq"
    SERILOG__MINIMUMLEVEL: "Information"
    SERILOG__WRITETO__0__NAME: "Console"
    SERILOG__WRITETO__1__NAME: "Seq"
    SERILOG__WRITETO__1__ARGS__SERVERURL: "http://localhost:5341"
    SERILOG__ENRICH__0: "FromLogContext"
    SERILOG__ENRICH__1: "WithMachineName"
    SERILOG__ENRICH__2: "WithEnvironmentName"
    SERILOG__ENRICH__3: "WithEnvironmentUserName"
    SERILOG__ENRICH__4: "WithApplicationName"
    SERILOG__PROPERTIES__APPLICATION: "AlbyOnContainers.Pollon.Development"

  sherlock:
    build:
      context: .
      dockerfile: src/AlbyOnContainers.Sherlock/Dockerfile
    container_name: sherlock
    restart: unless-stopped
    ports:
      - 5004:80
    environment:
      DOTNET_ENVIRONMENT: Development
      CONNECTIONSTRINGS__SEQ: "http://seq:5341"
      CONNECTIONSTRINGS__LUCIFER: "Host=postgres;Database=hulk;Username=postgres;Password=postgres;Port=5432"